baseURL = "https://example.com"
languageCode = "en"
title = "MyWebsite"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true

[pagination]
pagerSize = 5

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
